generic-service:
  nameOverride: hmpps-datahub-query-metrics
  productId: "DPS012"

  replicaCount: 1

  image:
    repository: ghcr.io/ministryofjustice/hmpps-datahub-query-metrics
    tag: app_version # override at deployment time
    port: 8080

  custommetrics:
    enabled: true
    scrapeInterval: 900s
    metricsPath: /metrics
    metricsPort: 9400

  ingress:
    enabled: true
    host: app-hostname.local # override per environment
    tlsSecretName: hmpps-datahub-query-metrics-cert

  # Environment variables to load into the deployment
  env:
    SERVER_PORT: "8080"
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.json
    REDSHIFT_DATA_DB: datamart
    AWS_STS_ENABLED: true

  namespace_secrets:
    hmpps-datahub-query-metrics-application-insights:
      APPLICATIONINSIGHTS_CONNECTION_STRING: "APPLICATIONINSIGHTS_CONNECTION_STRING"
    hmpps-datahub-query-metrics-datasource-details:
      ATHENA_WORKGROUP: athena_workgroup
      REDSHIFT_DATA_SECRETARN: "secretarn"
      REDSHIFT_JDBC_USER: "user"
      REDSHIFT_JDBC_PASSWORD: "password"
      REDSHIFT_JDBC_URL: "url"

generic-prometheus-alerts:
  targetApplication: digital-prison-reporting-prod
