---
generic-service:
  serviceAccountName: "datahub-query-metrics-test-cross-iam"

  ingress:
    host: hmpps-datahub-query-metrics-test.hmpps.service.justice.gov.uk
    modsecurity_enabled: true

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: "applicationinsights.dev.json"
    REDSHIFT_DATA_CLUSTER_ID: dpr-redshift-test

  allowlist:
    groups:
      - digital_staff_and_mojo
      - moj_cloud_platform

generic-prometheus-alerts:
  businessHoursOnly: true
  alertSeverity: digital-prison-reporting-test
