---
generic-service:
  serviceAccountName: "datahub-query-metrics-prod-cross-iam"

  ingress:
    host: hmpps-datahub-query-metrics.hmpps.service.justice.gov.uk
    modsecurity_enabled: true

  env:
    REDSHIFT_DATA_CLUSTER_ID: dpr-redshift-production
 
  allowlist:
    groups:
      - moj_cloud_platform

generic-prometheus-alerts:
  alertSeverity: digital-prison-reporting-prod
