---
generic-service:
  serviceAccountName: "datahub-query-metrics-preprod-cross-iam"

  ingress:
    host: hmpps-datahub-query-metrics-preprod.hmpps.service.justice.gov.uk
    modsecurity_enabled: true

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: "applicationinsights.dev.json"
    REDSHIFT_DATA_CLUSTER_ID: dpr-redshift-preproduction
    AWS_ACCOUNTID: "972272129531"

  allowlist:
    groups:
      - moj_cloud_platform

generic-prometheus-alerts:
  businessHoursOnly: true
  alertSeverity: digital-prison-reporting-preprod
